config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:create]
  end
  delete 'doses/:id', to: 'doses#destroy', as: "dose_delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: true
  validates :photo, presence: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates_uniqueness_of :ingredient_id, :scope => :cocktail_id
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = if params[:query]
      Cocktail.where('name LIKE ?', "%#{params[:query]}%")
    else
      Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end

  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :description)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="main-banner">
  <h1 id="banner-typed-text"></h1>
</div>


<div class="container" id="section01">
  <div class="row" data-aos="fade-in" data-aos-delay="50"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out">
    <h1 class="main-title text-center">Cocktails</h1>
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-md-4">
        <div class="card-item">
          <%= link_to cocktail_path(cocktail) do %>
            <div class="card-content card-image" style="background-image: url('<%= cl_image_path cocktail.photo %>');">
              <div class="card-title">
                <h4> <%= cocktail.name %></h4>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-12 col-md-4">
      <div class="special-card">
        <%= link_to "Add a Cocktail", new_cocktail_path ,class: "btn my-btn" %>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <h1>Add a new Cocktail</h1>
    <%= simple_form_for(@cocktail) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit "Add a Cocktail", class: "btn btn-primary" %>
      <%= link_to "Back to home", cocktails_path, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo %>');">
  <h1><%= @cocktail.name %></h1>
</div>
<div class="container">
  <div class="row" >
    <div class="col-md-8">
      <div class="cocktail-show-card">
        <h3>Decsription</h3>
        <p><%= @cocktail.description %></p>
        <%= link_to "Back to Cocktails", cocktails_path, class: "btn my-btn" %>
      </div>
      <div class="cocktail-show-card">
        <h3>Reviews</h3>
        <div class="list-group">
          <% @cocktail.reviews.each do |review| %>
            <li class="list-group-item">
              <small>
                <% count = 0 %>
                <% 5.times do %>
                  <% if review.rating > count %>
                    <i class="fas fa-star"></i>
                  <% else %>
                    <i class="far fa-star"></i>
                  <% end %>
                  <% count += 1 %>
                <% end %>
              </small>
              <p><%= review.content %></p>
            </li>
          <% end %>
        </div>
      </div>
      <div class="cocktail-show-card">
        <h2>Add a new Review</h2>
        <%= simple_form_for [@cocktail, @review] do |f| %>
          <%= f.input :content %>
          <%= f.input :rating %>
          <%= f.submit "add a review", class: "btn my-btn" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="cocktail-show-card">
        <h3>Ingredients</h3>
        <% @cocktail.doses.each do |dose| %>
          <%= dose.ingredient.name %> - <%= dose.description %> <%= link_to "(delete)", dose_delete_path(dose), method: :delete, class: "text-red" %> <br>
        <% end %>
        <br>
        <%= link_to "Add a dose",  new_cocktail_dose_path(@cocktail), class: "btn my-btn" %>
      </div>
    </div>

  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>

  <% if @dose.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @dose.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :description %>
  <%= f.association :ingredient, selected: 1 %>

  <%= f.submit "add a dose", class: "btn btn-primary" %>
  <%= link_to "Back to home", cocktails_path, class: "btn btn-danger" %>
<% end %>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <h1>Add a new dose</h1>
    <%= render "form" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Mister Cocktail", cocktails_path, class: "navbar-wagon-brand" %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Add Cocktail", new_cocktail_path ,class: "btn my-btn" %>
  </div>
</div>